apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
      - name: nodejs-api
        image: "DOCKER_HUB_REGISTRY/DOCKER_HUB_USERNAME/nodejs-api:RELEASE_VERSION"
        ports:
        - containerPort: 3000
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: nodejs-api-secrets
              key: WEATHER_API_KEY